[package]
name = "wasm-bindgen-webpack"
version = "0.0.1"
authors = [""]
repository = ""
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "=0.3.60"
wasm-bindgen = "=0.2.83"
